databases:
  - name: contactable
    databaseName: contactable
    user: contactable_user



services:
  - type: web
    name: contactable
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contactable
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false